-- 00_setup.sql
-- Create database, schemas and warehouse
USE ROLE SYSADMIN;

CREATE DATABASE IF NOT EXISTS RETAIL_DB;

CREATE OR REPLACE SCHEMA RETAIL_DB.RAW;
CREATE OR REPLACE SCHEMA RETAIL_DB.REF;
CREATE OR REPLACE SCHEMA RETAIL_DB.FINAL;
CREATE OR REPLACE SCHEMA RETAIL_DB.SEC;

CREATE OR REPLACE WAREHOUSE WH_RETAIL
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

USE DATABASE RETAIL_DB;
USE WAREHOUSE WH_RETAIL;

SHOW DATABASES LIKE 'RETAIL_DB';
SHOW SCHEMAS IN DATABASE RETAIL_DB;
SHOW WAREHOUSES LIKE 'WH_RETAIL';
