-- 01_stage_formats.sql
USE ROLE SYSADMIN;
USE DATABASE RETAIL_DB;
USE WAREHOUSE WH_RETAIL;

-- CSV / JSON file formats
CREATE OR REPLACE FILE FORMAT RETAIL_DB.RAW.FF_CSV
  TYPE = CSV
  SKIP_HEADER = 1
  FIELD_OPTIONALLY_ENCLOSED_BY = '"';

CREATE OR REPLACE FILE FORMAT RETAIL_DB.RAW.FF_NDJSON
  TYPE = JSON
  STRIP_OUTER_ARRAY = FALSE;

CREATE OR REPLACE FILE FORMAT RETAIL_DB.RAW.FF_CSV_INFERENCE
    TYPE = 'CSV'
    SKIP_HEADER = 1
    ENCODING = 'WINDOWS1252';

-- Internal stage
CREATE OR REPLACE STAGE RETAIL_DB.RAW.STAGE_RETAIL;

SHOW FILE FORMATS IN SCHEMA RETAIL_DB.RAW;
SHOW STAGES IN SCHEMA RETAIL_DB.RAW;
LIST @RETAIL_DB.RAW.STAGE_RETAIL;

-- Optional: External S3 stage using a Snowflake STORAGE INTEGRATION
-- Replace placeholders (ARN, bucket) with your AWS values and run as ACCOUNTADMIN
-- CREATE STORAGE INTEGRATION RETAIL_AWS_INTEGRATION
--   TYPE = EXTERNAL_STAGE
--   STORAGE_PROVIDER = 'S3'
--   ENABLED = TRUE
--   STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::123456789012:role/your-snowflake-role'
--   STORAGE_ALLOWED_LOCATIONS = ('s3://your-bucket/path/');

-- CREATE OR REPLACE STAGE RETAIL_DB.RAW.STAGE_RETAIL_S3
--   URL='s3://your-bucket/path/'
--   STORAGE_INTEGRATION = RETAIL_AWS_INTEGRATION
--   FILE_FORMAT = (TYPE = 'JSON');

-- Example usage:
-- LIST @RETAIL_DB.RAW.STAGE_RETAIL_S3;
