-- 05_governance_and_row_access.sql
USE ROLE SECURITYADMIN;

-- Roles
CREATE OR REPLACE ROLE ROLE_RETAIL_ADMIN;
CREATE OR REPLACE ROLE ROLE_RETAIL_INGEST;
CREATE OR REPLACE ROLE ROLE_RETAIL_TRANSFORM;
CREATE OR REPLACE ROLE ROLE_RETAIL_ANALYST;
CREATE OR REPLACE ROLE ROLE_RETAIL_PARTNER;

-- Role hierarchy (admin owns others)
GRANT ROLE ROLE_RETAIL_INGEST     TO ROLE ROLE_RETAIL_ADMIN;
GRANT ROLE ROLE_RETAIL_TRANSFORM  TO ROLE ROLE_RETAIL_ADMIN;
GRANT ROLE ROLE_RETAIL_ANALYST    TO ROLE ROLE_RETAIL_ADMIN;

-- Grants: DB / schema / warehouse usage
GRANT USAGE ON DATABASE RETAIL_DB TO ROLE ROLE_RETAIL_INGEST;
GRANT USAGE ON DATABASE RETAIL_DB TO ROLE ROLE_RETAIL_TRANSFORM;
GRANT USAGE ON DATABASE RETAIL_DB TO ROLE ROLE_RETAIL_ANALYST;
GRANT USAGE ON DATABASE RETAIL_DB TO ROLE ROLE_RETAIL_ADMIN;
GRANT USAGE ON DATABASE RETAIL_DB TO ROLE ROLE_RETAIL_PARTNER;

GRANT USAGE ON SCHEMA RETAIL_DB.RAW   TO ROLE ROLE_RETAIL_INGEST;
GRANT USAGE ON SCHEMA RETAIL_DB.REF   TO ROLE ROLE_RETAIL_TRANSFORM;
GRANT USAGE ON SCHEMA RETAIL_DB.FINAL TO ROLE ROLE_RETAIL_ANALYST;
GRANT USAGE ON SCHEMA RETAIL_DB.SEC   TO ROLE ROLE_RETAIL_ADMIN;
GRANT USAGE ON SCHEMA RETAIL_DB.FINAL TO ROLE ROLE_RETAIL_PARTNER;

GRANT USAGE ON WAREHOUSE WH_RETAIL TO ROLE ROLE_RETAIL_INGEST;
GRANT USAGE ON WAREHOUSE WH_RETAIL TO ROLE ROLE_RETAIL_TRANSFORM;
GRANT USAGE ON WAREHOUSE WH_RETAIL TO ROLE ROLE_RETAIL_ANALYST;
GRANT USAGE ON WAREHOUSE WH_RETAIL TO ROLE ROLE_RETAIL_ADMIN;
GRANT USAGE ON WAREHOUSE WH_RETAIL TO ROLE ROLE_RETAIL_PARTNER;

-- Sample object privileges (tweak for production least-privilege)
GRANT CREATE TABLE, CREATE STAGE, CREATE FILE FORMAT
  ON SCHEMA RETAIL_DB.RAW TO ROLE ROLE_RETAIL_INGEST;

GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE
  ON ALL TABLES IN SCHEMA RETAIL_DB.RAW TO ROLE ROLE_RETAIL_INGEST;
GRANT SELECT
  ON FUTURE TABLES IN SCHEMA RETAIL_DB.RAW TO ROLE ROLE_RETAIL_INGEST;

GRANT CREATE TABLE, CREATE VIEW ON SCHEMA RETAIL_DB.REF   TO ROLE ROLE_RETAIL_TRANSFORM;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA RETAIL_DB.FINAL TO ROLE ROLE_RETAIL_TRANSFORM;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA RETAIL_DB.REF TO ROLE ROLE_RETAIL_TRANSFORM;
GRANT SELECT ON FUTURE TABLES IN SCHEMA RETAIL_DB.REF TO ROLE ROLE_RETAIL_TRANSFORM;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA RETAIL_DB.FINAL TO ROLE ROLE_RETAIL_TRANSFORM;
GRANT SELECT ON FUTURE TABLES IN SCHEMA RETAIL_DB.FINAL TO ROLE ROLE_RETAIL_TRANSFORM;

GRANT SELECT ON ALL TABLES IN SCHEMA RETAIL_DB.FINAL TO ROLE ROLE_RETAIL_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA RETAIL_DB.FINAL TO ROLE ROLE_RETAIL_ANALYST;

-- Tags and sensitive data labeling
USE ROLE ROLE_RETAIL_ADMIN;
USE DATABASE RETAIL_DB;
USE SCHEMA SEC;

CREATE OR REPLACE TAG TAG_CLASSIFICATION;  -- PUBLIC/INTERNAL/CONFIDENTIAL
CREATE OR REPLACE TAG TAG_PII;             -- YES/NO

-- Row access policy example
USE ROLE ROLE_RETAIL_ADMIN;
USE DATABASE RETAIL_DB;
USE SCHEMA SEC;

CREATE OR REPLACE TABLE REGION_ACCESS (
  role_name STRING,
  country   STRING
);

CREATE OR REPLACE ROW ACCESS POLICY RAP_REGION
AS (country STRING) RETURNS BOOLEAN ->
  EXISTS (
    SELECT 1
    FROM RETAIL_DB.SEC.REGION_ACCESS a
    WHERE a.role_name = CURRENT_ROLE()
      AND a.country = country
  );

ALTER TABLE IF EXISTS RETAIL_DB.FINAL.KPI_DAILY_REGION_SALES
  ADD ROW ACCESS POLICY RETAIL_DB.SEC.RAP_REGION ON (country);

-- Notes:
-- Ensure REGION_ACCESS is populated and role names exactly match runtime roles.
